import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#6B7280',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
  },
  closeButton: {
    padding: 4,
    marginTop: 4,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'flex-start',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 8,
  },
  togglesSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  toggleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  toggleLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
  },
  overlappingAvatars: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
  },
  singleAvatarContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
    overflow: 'hidden',
  },
  singleAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
  },
  singleAvatarDefault: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 24,
  },
  singleAvatarText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#6B7280',
  },
  overlappingAvatarContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    overflow: 'hidden',
  },
  overlappingAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
  },
  overlappingAvatarDefault: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlappingAvatarText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  stackedNames: {
    flex: 1,
    justifyContent: 'center',
    marginRight: 12,
  },
  stackedNameText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    lineHeight: 22,
  },
  tiebreakOverlay: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 32,
    height: 32,
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  tiebreakOverlayInput: {
    width: '100%',
    height: '100%',
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    textAlign: 'center',
    padding: 0,
  },
  tiebreakInputDisabled: {
    backgroundColor: '#E5E7EB',
    opacity: 0.6,
  },
  teamsHeaderSection: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  teamHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  teamHeaderPlayers: {
    flex: 1,
    gap: 12,
  },
  teamHeaderPlayerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  teamHeaderAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  teamHeaderPlayerName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    flex: 1,
  },
  vsDividerContainer: {
    paddingHorizontal: 16,
  },
  vsText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#9CA3AF',
  },
  partnershipInfo: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  partnershipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  partnershipPlayer: {
    alignItems: 'center',
    flex: 1,
  },
  partnershipAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginBottom: 8,
  },
  partnershipName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  captainLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
  },
  captainText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#92400E',
  },
  partnerText: {
    fontSize: 11,
    color: '#6B7280',
  },
  partnershipDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 16,
  },
  warningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    padding: 10,
    backgroundColor: '#FEF3C7',
    borderRadius: 8,
  },
  warningBannerText: {
    flex: 1,
    fontSize: 12,
    color: '#92400E',
    fontWeight: '500',
  },
  setsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
  },
  setsHeaderLabel: {
    width: 100,
  },
  setsHeaderLabelText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
    letterSpacing: 0.5,
  },
  setsHeaderNumbers: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'flex-end',
    gap: 12,
  },
  setNumberHeaderBox: {
    width: 64,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  setNumberHeaderText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6B7280',
    width: 64,
    textAlign: 'center',
  },
  teamRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  playersColumn: {
    width: 80,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  teamNameColumn: {
    width: 120,
    justifyContent: 'center',
    paddingRight: 12,
  },
  teamNameText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111827',
    textAlign: 'left',
  },
  playerContainer: {
    alignItems: 'center',
    width: 48,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginBottom: 4,
    overflow: 'visible',
    position: 'relative',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
  },
  defaultAvatar: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 18,
  },
  defaultAvatarText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6B7280',
  },
  captainBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFD700',
  },
  playerName: {
    fontSize: 11,
    color: '#6B7280',
    fontWeight: '500',
    textAlign: 'center',
  },
  scoresColumn: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  scoreInputWrapper: {
    position: 'relative',
    width: 64,
    height: 64,
  },
  scoreInput: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#BFDBFE',
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
  },
  scoreInputDisabled: {
    backgroundColor: '#E5E7EB',
    borderColor: '#D1D5DB',
    opacity: 0.5,
  },
  winIndicator: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#10B981',
    borderRadius: 10,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  winIndicatorText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  summarySection: {
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  summaryTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 12,
  },
  summaryInput: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    fontSize: 14,
    color: '#111827',
    minHeight: 80,
    textAlignVertical: 'top',
  },
  // Comments styles for review mode
  reviewNoCommentsContainer: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  reviewNoCommentsText: {
    marginTop: 8,
    fontSize: 14,
    color: '#9CA3AF',
  },
  reviewCommentsListContainer: {
    marginBottom: 12,
  },
  viewMoreCommentsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 4,
  },
  viewMoreCommentsText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FEA04D',
  },
  reviewCommentItemContainer: {
    flexDirection: 'row',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  reviewCommentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E5E7EB',
  },
  reviewCommentDefaultAvatar: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewCommentDefaultAvatarText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  reviewCommentContentContainer: {
    flex: 1,
    marginLeft: 10,
  },
  reviewCommentHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reviewCommentHeaderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  reviewCommentAuthorName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1F2937',
    maxWidth: 120,
  },
  reviewCommentTimestamp: {
    fontSize: 12,
    color: '#9CA3AF',
    marginLeft: 4,
  },
  reviewCommentMenuWrapper: {
    position: 'relative',
    zIndex: 10,
  },
  reviewCommentMenuButton: {
    padding: 4,
  },
  reviewCommentDropdownMenu: {
    position: 'absolute',
    top: 24,
    right: 0,
    backgroundColor: '#FFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    minWidth: 100,
    zIndex: 100,
  },
  reviewCommentDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 8,
  },
  reviewCommentDropdownItemText: {
    fontSize: 14,
    color: '#374151',
  },
  reviewCommentDeleteText: {
    color: '#EF4444',
  },
  reviewCommentDropdownDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
  },
  reviewCommentTextContent: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
    marginTop: 2,
  },
  reviewEditCommentContainer: {
    marginTop: 8,
  },
  reviewEditCommentInput: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    color: '#374151',
    minHeight: 60,
    maxHeight: 120,
    textAlignVertical: 'top',
    backgroundColor: '#F9FAFB',
  },
  reviewEditCommentActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 8,
    gap: 8,
  },
  reviewEditCancelButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  reviewEditCancelButtonText: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  reviewEditSaveButton: {
    backgroundColor: '#10B981',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
    minWidth: 70,
    alignItems: 'center',
  },
  reviewEditSaveButtonDisabled: {
    backgroundColor: '#D1D5DB',
  },
  reviewEditSaveButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFF',
  },
  reviewCommentInputWrapper: {
    marginTop: 12,
  },
  reviewCommentInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F6FAFC',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    paddingLeft: 14,
    paddingRight: 10,
    height: 48,
  },
  reviewCommentInput: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    paddingVertical: 0,
    marginRight: 8,
  },
  reviewCommentSendButton: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoContainer: {
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 12,
    backgroundColor: '#EFF6FF',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 8,
  },
  infoText: {
    flex: 1,
    fontSize: 12,
    color: '#1E40AF',
    lineHeight: 16,
  },
  disclaimerContainer: {
    marginHorizontal: 20,
    marginBottom: 16,
    alignItems: 'center',
  },
  disclaimerText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#DC2626',
    textAlign: 'center',
  },
  submitButton: {
    marginHorizontal: 20,
    marginBottom: 32,
    backgroundColor: '#F59E0B',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  submitButtonDisabled: {
    opacity: 0.5,
  },
  submitButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  reviewActions: {
    flexDirection: 'row',
    gap: 12,
    marginHorizontal: 20,
    marginBottom: 32,
  },
  disputeButtonLarge: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: '#FEF2F2',
    borderWidth: 2,
    borderColor: '#FEE2E2',
  },
  disputeButtonLargeText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#DC2626',
  },
  approveButtonLarge: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: '#FEA04D',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  approveButtonLargeText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#2B2929',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  // Walkover styles
  walkoverContainer: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
  },
  // Singles walkover compact indicator
  singlesWalkoverIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 16,
    gap: 6,
  },
  singlesWalkoverAvatar: {
    width: 20,
    height: 20,
    borderRadius: 10,
    overflow: 'hidden',
  },
  singlesWalkoverAvatarImage: {
    width: '100%',
    height: '100%',
  },
  singlesWalkoverAvatarDefault: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  singlesWalkoverAvatarText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#6B7280',
  },
  singlesWalkoverName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111827',
  },
  singlesWalkoverLabel: {
    fontSize: 13,
    color: '#6B7280',
  },
  // Walkover view mode styles
  walkoverViewContainer: {
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  walkoverViewIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#FEF3C7',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  walkoverViewTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 16,
  },
  walkoverViewPlayerName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#F59E0B',
  },
  walkoverViewDidntPlay: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 20,
  },
  walkoverViewReasonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  walkoverViewReasonLabel: {
    fontSize: 14,
    color: '#6B7280',
  },
  walkoverViewReasonDetail: {
    fontSize: 14,
    fontStyle: 'italic',
    color: '#9CA3AF',
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  walkoverSection: {
    marginBottom: 24,
  },
  walkoverSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 12,
  },
  walkoverTeamSelection: {
    gap: 12,
  },
  walkoverTeamOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  walkoverTeamOptionSelected: {
    borderColor: '#F59E0B',
    backgroundColor: '#FFFBEB',
  },
  walkoverTeamAvatars: {
    flexDirection: 'row',
    marginRight: 12,
  },
  walkoverAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    overflow: 'hidden',
  },
  walkoverAvatarImage: {
    width: '100%',
    height: '100%',
  },
  walkoverAvatarDefault: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  walkoverAvatarText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  walkoverTeamNames: {
    flex: 1,
  },
  walkoverTeamNameText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    lineHeight: 20,
  },
  walkoverCheckmark: {
    marginLeft: 8,
  },
  walkoverReasonGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  walkoverReasonOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: '#F9FAFB',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    gap: 6,
  },
  walkoverReasonOptionSelected: {
    borderColor: '#F59E0B',
    backgroundColor: '#FFFBEB',
  },
  walkoverReasonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#6B7280',
  },
  walkoverReasonTextSelected: {
    color: '#92400E',
  },
  walkoverDetailInput: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    fontSize: 14,
    color: '#111827',
    minHeight: 80,
    textAlignVertical: 'top',
  },
  // Disputed banner styles
  disputedBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 16,
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FEE2E2',
  },
  disputedBannerContent: {
    flex: 1,
  },
  disputedBannerTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#DC2626',
    marginBottom: 4,
  },
  disputedBannerText: {
    fontSize: 13,
    color: '#991B1B',
    lineHeight: 18,
  },
  // Dispute details styles
  disputeDetailsContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#FEE2E2',
  },
  disputeDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  disputeDetailLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#991B1B',
    width: 100,
  },
  disputeDetailValue: {
    fontSize: 12,
    color: '#7F1D1D',
    flex: 1,
  },
  disputeReasonContainer: {
    marginBottom: 8,
  },
  disputeReasonText: {
    fontSize: 12,
    color: '#7F1D1D',
    fontStyle: 'italic',
    marginTop: 4,
    lineHeight: 16,
  },
  disputeStatusBadge: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  disputeStatusText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#DC2626',
    textTransform: 'uppercase',
  },
  // Casual Play / Friendly Match toggle styles
  casualPlayToggleSection: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  pillToggleContainer: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: 25,
    padding: 4,
    position: 'relative',
  },
  pillToggleSlider: {
    position: 'absolute',
    top: 4,
    left: 4,
    bottom: 4,
    backgroundColor: '#FEA04D',
    borderRadius: 20,
  },
  pillToggleButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    zIndex: 1,
  },
  pillToggleText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9CA3AF',
    textAlign: 'center',
  },
  pillToggleTextActive: {
    color: '#FFFFFF',
  },
  casualPlayHint: {
    flex: 1,
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 18,
  },
  // Casual Play container and content styles
  casualPlayContainer: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
  },
  gameSummarySection: {
    marginBottom: 24,
  },
  gameSummaryTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FEA04D',
    marginBottom: 12,
  },
  gameSummaryItem: {
    marginBottom: 8,
  },
  gameSummaryText: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  gameSummaryName: {
    fontWeight: '600',
    color: '#111827',
  },
  gameSummaryColon: {
    color: '#9CA3AF',
  },
  casualCommentInputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 24,
    paddingRight: 8,
  },
  casualCommentInput: {
    flex: 1,
    padding: 14,
    fontSize: 14,
    color: '#111827',
    minHeight: 100,
    textAlignVertical: 'top',
  },
  sendIconButton: {
    padding: 12,
    marginTop: 4,
  },
  confirmButton: {
    backgroundColor: '#FEA04D',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  confirmButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 12,
  },
  commentItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
    padding: 12,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
  },
  commentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 12,
    overflow: 'hidden',
  },
  commentAvatarImage: {
    width: '100%',
    height: '100%',
  },
  commentAvatarDefault: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  commentAvatarText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
  },
  commentContent: {
    flex: 1,
  },
  commentAuthor: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  commentText: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 20,
  },
  commentInputSection: {
    marginBottom: 24,
  },
  casualPlayCommentInput: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    fontSize: 14,
    color: '#111827',
    minHeight: 100,
  },
  // Team selection styles
  teamSelectionContainer: {
    paddingHorizontal: 20,
    paddingTop: 16,
    marginBottom: 16,
  },
  teamSelectionHint: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 16,
  },
  teamSection: {
    marginBottom: 20,
  },
  teamLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 10,
  },
  playerSelectItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    marginBottom: 8,
  },
  playerSelected: {
    borderColor: '#FEA04D',
    backgroundColor: '#FFFBEB',
  },
  playerDisabled: {
    opacity: 0.4,
  },
  playerSelectAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 12,
    overflow: 'hidden',
  },
  playerSelectAvatarImage: {
    width: '100%',
    height: '100%',
  },
  playerSelectAvatarDefault: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playerSelectAvatarText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  playerSelectName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500',
    color: '#111827',
  },
  playerSelectNameDisabled: {
    color: '#9CA3AF',
  },
  teamValidationText: {
    fontSize: 13,
    color: '#DC2626',
    textAlign: 'center',
    marginTop: 8,
  },
  // Friendly Match UI styles
  friendlyMatchContainer: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 32,
  },
  friendlyMatchHeader: {
    marginBottom: 16,
  },
  friendlyMatchTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FEA04D',
    marginBottom: 4,
  },
  friendlyMatchSubtitle: {
    fontSize: 13,
    color: '#FEA04D',
  },
  friendlyTogglesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  friendlyToggleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  friendlyToggleLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
  },
  friendlySetsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  friendlySetsHeaderLabel: {
    width: 120,
  },
  friendlySetsHeaderText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
    letterSpacing: 0.5,
  },
  friendlySetsHeaderNumbers: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  friendlySetNumberText: {
    width: 56,
    fontSize: 16,
    fontWeight: '600',
    color: '#6B7280',
    textAlign: 'center',
  },
  friendlyTeamRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  friendlyTeamAvatars: {
    flexDirection: 'row',
    width: 50,
    marginRight: 6,
  },
  friendlyAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    overflow: 'hidden',
  },
  friendlyAvatarImage: {
    width: '100%',
    height: '100%',
  },
  friendlyAvatarDefault: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  friendlyAvatarPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
  },
  friendlyAvatarText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#6B7280',
  },
  friendlyDropdownsColumn: {
    flex: 1,
    gap: 2,
  },
  dropdownWrapper: {
    position: 'relative',
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  dropdownButtonText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#111827',
  },
  dropdownPlaceholderText: {
    color: '#9CA3AF',
  },
  dropdownMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginTop: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
  },
  dropdownMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    gap: 10,
  },
  dropdownMenuItemLast: {
    borderBottomWidth: 0,
  },
  dropdownMenuItemAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    overflow: 'hidden',
  },
  dropdownMenuItemAvatarImage: {
    width: '100%',
    height: '100%',
  },
  dropdownMenuItemAvatarDefault: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownMenuItemAvatarText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6B7280',
  },
  dropdownMenuItemText: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    fontWeight: '500',
  },
  dropdownMenuItemTextDisabled: {
    color: '#D1D5DB',
  },
  dropdownMenuItemDisabled: {
    backgroundColor: '#FAFAFA',
  },
  dropdownMenuItemAvatarDisabled: {
    opacity: 0.4,
  },
  dropdownMenuItemCheck: {
    marginLeft: 'auto',
  },
  friendlyScoresColumn: {
    flexDirection: 'row',
    gap: 10,
  },
  friendlyScoreInput: {
    width: 56,
    height: 56,
    backgroundColor: '#EBF5FF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#BFDBFE',
    fontSize: 22,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
  },
  friendlyScoreInputDisabled: {
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
    opacity: 0.5,
  },
  friendlyScoreSection: {
    position: 'relative',
  },
  friendlyScoreSectionDisabled: {
    opacity: 0.4,
  },
  didntPlayOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
    borderRadius: 12,
  },
  didntPlayOverlayText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6B7280',
  },
  friendlyDivider: {
    height: 1,
    backgroundColor: '#FEA04D',
    marginVertical: 20,
    opacity: 0.3,
  },
});
