import { StyleSheet } from 'react-native';
import {
  scale,
  verticalScale,
  moderateScale,
} from '@/core/utils/responsive';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    paddingBottom: verticalScale(16),
    borderBottomLeftRadius: moderateScale(24),
    borderBottomRightRadius: moderateScale(24),
    overflow: 'hidden',
    position: 'relative',
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(8),
    gap: scale(8),
  },
  backButton: {
    padding: moderateScale(4),
  },
  headerMatchType: {
    flex: 1,
    fontSize: moderateScale(16),
    fontWeight: '600',
    color: '#FFFFFF',
  },
  leagueBadge: {
    backgroundColor: '#FEA04D',
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(4),
    borderRadius: moderateScale(4),
  },
  leagueBadgeText: {
    color: '#FFFFFF',
    fontSize: moderateScale(10),
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  headerContent: {
    paddingHorizontal: scale(24),
    marginTop: verticalScale(4),
  },
  headerLeagueName: {
    fontSize: moderateScale(20),
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: verticalScale(4),
  },
  headerSeason: {
    fontSize: moderateScale(14),
    color: 'rgba(255,255,255,0.8)',
  },
  headerIcon: {
    position: 'absolute',
    bottom: verticalScale(-10),
    right: scale(10),
    opacity: 0.8,
  },
  scrollContent: {
    flex: 1,
  },
  scrollContentContainer: {
    paddingTop: verticalScale(24),
    paddingBottom: verticalScale(32),
  },
  participantsSection: {
    paddingHorizontal: scale(24),
    marginBottom: verticalScale(24),
  },
  playersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  playerSection: {
    alignItems: 'center',
    flex: 1,
  },
  teamSection: {
    alignItems: 'center',
    flex: 1,
  },
  teamPlayers: {
    flexDirection: 'row',
    gap: scale(12),
  },
  doublesPlayerContainer: {
    alignItems: 'center',
    maxWidth: scale(60),
  },
  playerAvatarWrapper: {
    position: 'relative',
    marginBottom: verticalScale(6),
  },
  playerAvatar: {
    width: scale(48),
    height: verticalScale(48),
    borderRadius: moderateScale(24),
    overflow: 'hidden',
  },
  pendingBadge: {
    position: 'absolute',
    bottom: verticalScale(-2),
    right: scale(-2),
    backgroundColor: '#FEF3C7',
    borderRadius: moderateScale(10),
    width: scale(20),
    height: verticalScale(20),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: moderateScale(2),
    borderColor: '#FFFFFF',
  },
  acceptedBadge: {
    position: 'absolute',
    bottom: verticalScale(-2),
    right: scale(-2),
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(10),
    width: scale(20),
    height: verticalScale(20),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: moderateScale(2),
    borderColor: '#FFFFFF',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  defaultAvatar: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  defaultAvatarText: {
    fontSize: moderateScale(18),
    fontWeight: '600',
    color: '#6B7280',
  },
  emptySlot: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: moderateScale(2),
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    borderRadius: moderateScale(24),
  },
  playerName: {
    fontSize: moderateScale(12),
    fontWeight: '600',
    color: '#111827',
    textAlign: 'center',
  },
  vsContainer: {
    paddingHorizontal: scale(16),
  },
  vsText: {
    fontSize: moderateScale(12),
    color: '#6B7280',
    fontWeight: '500',
  },
  verticalDivider: {
    width: scale(1),
    height: verticalScale(80),
    backgroundColor: '#E2E2E2',
    marginHorizontal: scale(16),
  },
  divider: {
    height: verticalScale(1),
    backgroundColor: '#E2E2E2',
    marginHorizontal: scale(24),
  },
  detailRow: {
    flexDirection: 'row',
    paddingHorizontal: scale(24),
    paddingVertical: verticalScale(20),
    gap: scale(16),
  },
  iconContainer: {
    width: scale(24),
    alignItems: 'center',
  },
  detailContent: {
    flex: 1,
  },
  detailTitle: {
    fontSize: moderateScale(15),
    fontWeight: '600',
    color: '#111827',
    marginBottom: verticalScale(4),
  },
  dateTimeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    marginBottom: verticalScale(4),
  },
  statusBadge: {
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(3),
    borderRadius: moderateScale(12),
  },
  statusBadgeText: {
    fontSize: moderateScale(11),
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  detailSubtitle: {
    fontSize: moderateScale(13),
    color: '#6B7280',
    lineHeight: verticalScale(18),
  },
  openToRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(12),
    gap: scale(12),
  },
  openToLabel: {
    fontSize: moderateScale(13),
    color: '#6B7280',
    fontWeight: '400',
    minWidth: scale(60),
  },
  restrictionChipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: scale(6),
    flex: 1,
  },
  genderRestrictionChip: {
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(6),
    borderRadius: moderateScale(16),
    backgroundColor: '#FEF3E2',
    borderWidth: moderateScale(1),
    borderColor: '#FED7AA',
  },
  genderRestrictionChipText: {
    fontSize: moderateScale(12),
    fontWeight: '500',
    color: '#374151',
  },
  skillRestrictionChip: {
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(6),
    borderRadius: moderateScale(16),
    backgroundColor: '#E0F2FE',
    borderWidth: moderateScale(1),
    borderColor: '#BAE6FD',
  },
  skillRestrictionChipText: {
    fontSize: moderateScale(12),
    fontWeight: '500',
    color: '#374151',
  },
  detailAddress: {
    fontSize: moderateScale(13),
    color: '#6B7280',
    lineHeight: verticalScale(18),
    marginBottom: verticalScale(8),
  },
  courtStatusContainer: {
    flexDirection: 'row',
  },
  courtBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(4),
    borderRadius: moderateScale(12),
    gap: scale(4),
  },
  courtBadgeText: {
    fontSize: moderateScale(12),
    color: '#166534',
    fontWeight: '500',
  },
  descriptionSection: {
    paddingHorizontal: scale(24),
    paddingVertical: verticalScale(20),
    backgroundColor: '#FFFFFF',
    marginHorizontal: scale(24),
    borderRadius: moderateScale(12),
  },
  descriptionTitle: {
    fontSize: moderateScale(15),
    fontWeight: '600',
    color: '#111827',
    marginBottom: verticalScale(8),
  },
  descriptionText: {
    fontSize: moderateScale(14),
    color: '#6B7280',
    lineHeight: verticalScale(20),
  },
  noDescriptionText: {
    fontStyle: 'italic',
    color: '#9CA3AF',
  },
  partnershipStatus: {
    marginHorizontal: scale(24),
    marginTop: verticalScale(20),
  },
  successBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    padding: moderateScale(12),
    borderRadius: moderateScale(12),
    gap: scale(8),
  },
  successBannerText: {
    flex: 1,
    fontSize: moderateScale(14),
    color: '#166534',
    fontWeight: '500',
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF2F2',
    padding: moderateScale(12),
    borderRadius: moderateScale(12),
    gap: scale(8),
  },
  errorBannerText: {
    flex: 1,
    fontSize: moderateScale(14),
    color: '#DC2626',
    fontWeight: '500',
  },
  autoApprovalInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
    marginTop: verticalScale(6),
  },
  autoApprovalInlineText: {
    fontSize: moderateScale(12),
    color: '#F59E0B',
    fontWeight: '500',
  },
  walkoverInfoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFBEB',
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(10),
    borderRadius: moderateScale(8),
    marginTop: verticalScale(10),
    gap: scale(8),
  },
  walkoverInfoContent: {
    flex: 1,
  },
  walkoverInfoText: {
    fontSize: moderateScale(13),
    fontWeight: '600',
    color: '#92400E',
  },
  walkoverReasonText: {
    fontSize: moderateScale(12),
    color: '#B45309',
    marginTop: verticalScale(2),
  },
  draftStatusBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: scale(12),
    marginHorizontal: scale(24),
    marginTop: verticalScale(16),
    padding: moderateScale(16),
    borderRadius: moderateScale(12),
    backgroundColor: '#F9FAFB',
    borderWidth: moderateScale(1),
    borderColor: '#E5E7EB',
  },
  draftStatusContent: {
    flex: 1,
  },
  draftStatusTitle: {
    fontSize: moderateScale(15),
    fontWeight: '600',
    color: '#374151',
    marginBottom: verticalScale(4),
  },
  draftStatusText: {
    fontSize: moderateScale(13),
    color: '#6B7280',
    lineHeight: verticalScale(18),
  },
  draftStatusHint: {
    fontSize: moderateScale(12),
    color: '#9CA3AF',
    fontStyle: 'italic',
    marginTop: verticalScale(8),
  },
  voidStatusBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: scale(12),
    marginHorizontal: scale(24),
    marginTop: verticalScale(16),
    padding: moderateScale(16),
    borderRadius: moderateScale(12),
    backgroundColor: '#FEF2F2',
    borderWidth: moderateScale(1),
    borderColor: '#FEE2E2',
  },
  voidStatusContent: {
    flex: 1,
  },
  voidStatusTitle: {
    fontSize: moderateScale(15),
    fontWeight: '600',
    color: '#DC2626',
    marginBottom: verticalScale(4),
  },
  voidStatusText: {
    fontSize: moderateScale(13),
    color: '#991B1B',
    lineHeight: verticalScale(18),
  },
  unfinishedStatusBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: scale(12),
    marginHorizontal: scale(24),
    marginTop: verticalScale(16),
    padding: moderateScale(16),
    borderRadius: moderateScale(12),
    backgroundColor: '#FFFBEB',
    borderWidth: moderateScale(1),
    borderColor: '#FEF3C7',
  },
  unfinishedStatusContent: {
    flex: 1,
  },
  unfinishedStatusTitle: {
    fontSize: moderateScale(15),
    fontWeight: '600',
    color: '#D97706',
    marginBottom: verticalScale(4),
  },
  unfinishedStatusText: {
    fontSize: moderateScale(13),
    color: '#92400E',
    lineHeight: verticalScale(18),
  },
  reportButton: {
    alignItems: 'center',
    paddingVertical: verticalScale(24),
  },
  reportButtonText: {
    fontSize: moderateScale(13),
    color: '#6B7280',
  },
  footer: {
    paddingHorizontal: scale(24),
    paddingTop: verticalScale(16),
    backgroundColor: '#FFFFFF',
    borderTopWidth: moderateScale(1),
    borderTopColor: '#F3F4F6',
  },
  buttonGroup: {
    gap: verticalScale(12),
  },
  testButton: {
    paddingVertical: verticalScale(12),
    borderRadius: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: moderateScale(2),
    borderColor: '#8B5CF6',
  },
  testButtonText: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: '#FFFFFF',
  },
  joinButton: {
    paddingVertical: verticalScale(16),
    borderRadius: moderateScale(16),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: verticalScale(2) },
    shadowOpacity: 0.1,
    shadowRadius: moderateScale(4),
    elevation: 2,
  },
  joinButtonWithIcon: {
    flexDirection: 'row',
    gap: scale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  joinButtonDisabled: {
    opacity: 0.5,
  },
  joinButtonText: {
    fontSize: moderateScale(17),
    fontWeight: '700',
    color: '#2B2929',
  },
  completedMatchButtons: {
    flexDirection: 'row',
    gap: scale(12),
  },
  completedButton: {
    flex: 1,
  },
  shareButton: {
    backgroundColor: '#10B981',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomSheetBackground: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: moderateScale(20),
    borderTopRightRadius: moderateScale(20),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: verticalScale(60),
  },
  loadingText: {
    marginTop: verticalScale(12),
    fontSize: moderateScale(14),
    color: '#6B7280',
  },
});
